import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { HeroHeader } from "@/components/header";
import FooterSection from "@/components/footer";
import WhatsappWrapper from "@/components/whatsapp-chat-wrapper";

const roboto = Roboto({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "SKYRIM TRAVELS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <HeroHeader></HeroHeader>
        {children}
        <div id="contact">
         <WhatsappWrapper/>
          <FooterSection></FooterSection>
        </div>
      </body>
    </html>
  );
}
